pipeline {
    agent { node { label 'jenkins-slave-rohan' } }
    stages {
        stage('build') {
            steps {
                echo env.STAGE_NAME
            }
        }
        stage('test'){
            steps {
                echo env.STAGE_NAME
            }
        }
    }
}
