pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                bat 'mkdir jenkins-slave-node'
                bat 'cd jenkins-slave-node'
                bat 'type nul > problem2.txt'
                bat 'echo Hello Jenkins! >> problem2.txt'
            }
        }
    }
}
