version: '3.8'
services:
  backend:
    build: 
      context: ./node-backend
    ports:
      - "5000:5000"
    volumes:
      - C:\Users\Rohan\Documents\Docker_Exercise\Problem6\node-backend:/node-backend
      - /backend/node_modules
  frontend:
    build: 
      context: ./react-frontend
    ports:
      - "3000:3000"
    volumes:
      - C:\Users\Rohan\Documents\Docker_Exercise\Problem6\react-frontend:/react-frontend
      - /react-app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    
  