import groovy.json.JsonSlurperClassic
pipeline {
    agent any
    
    stages {
        stage('Hello') {
            steps {
                script {
                    def get = new URL("https://jsonplaceholder.typicode.com/todos").openConnection();
                    get.requestMethod = "GET"
                    def data = get.getInputStream().getText()
                    def jsonObject = new JsonSlurperClassic().parseText(data)
                    for(item in jsonObject){
                    if(item.completed == false){
                        println(item)
                        }
                    }
                }
            }
        }
    }
}
